import React from 'react';
import { Text, Linking } from 'react-native';
// import { withTheme } from "@callstack/react-theme-provider";
import { PrivacyPolicy } from '../views'

const style =  theme => ({
    textColor: {
        //color: theme.colors.contrast,
    },
    text: {
        //color: theme.colors.contrast,
        paddingBottom: 15
    },
    bold: {
        fontWeight: 'bold'
    },
    underline: {
        textDecorationLine: 'underline'
    },
    link: {
        textDecorationLine: 'underline',
        // color:  theme.colors.secondaryContrast
    }
});

const EulaTextComponent = props => {
    const  classes = style(props.theme);
    return (
    <>
        <Text style={{...classes.bold, ...classes.text, ...props.textStyle}}>J. J. KELLER WEBSITE AND APPLICATIONS END USER LICENSE AGREEMENT AND TERMS OF USE</Text>
        <Text style={{...classes.text, ...props.textStyle}}>Last Modified on June 10, 2019</Text>
        <Text style={{...classes.text, ...props.textStyle}}>This End User License Agreement and Terms of Use ("Agreement") is a binding agreement between you ("End User" or "you") and J. J. Keller & Associates, Inc. ("J. J. Keller," “us,” “our,” or “we”). This Agreement governs your use of the J. J. Keller's websites, however accessed (collectively, the “Website”), and all other online, mobile or other device applications (including all related documentation, the "Application").</Text>
        <Text style={{...classes.text, ...props.textStyle}}>BY USING THE WEBSITE AND/OR INSTALLING OR USING THE APPLICATION, YOU (A) ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND THIS AGREEMENT; (B) REPRESENT THAT YOU ARE OF LEGAL AGE TO ENTER INTO A BINDING AGREEMENT; AND (C) ACCEPT THIS AGREEMENT AND AGREE THAT YOU ARE LEGALLY BOUND BY ITS TERMS. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT DOWNLOAD, INSTALL OR USE THE APPLICATION.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>1.  <Text style={classes.underline}>License Grant</Text>. Subject to the terms of this Agreement, J. J. Keller grants you a limited, royalty-free, non-exclusive, nontransferable and revocable license to:</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(a)  use the Website;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(b)  download, install, and use the Application for your individual use on a single mobile or other device (including computer or tablet) owned or otherwise controlled by you ("Device") strictly in accordance with the Application's documentation; and</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(c)  access, stream, download, and use on such Device the products, services, features, functionality, and content accessible or hosted on the Website and made available in or otherwise accessible through the Application, strictly in accordance with this Agreement.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>2.  <Text style={classes.underline}>License Restrictions</Text>. You shall not:</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(a)  copy the Application, except as expressly permitted by this license;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(b)  modify, translate, adapt, or otherwise create derivative works or improvements, whether or not patentable, of the Application;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(c)  reverse engineer, disassemble, decompile, decode, or otherwise attempt to derive or gain access to the source code of the Application or any part thereof;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(d)  remove, delete, alter, or obscure any trademarks or any copyright, trademark, patent, or other intellectual property or proprietary rights notices from the Application, including any copy thereof;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(e)  rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Application, or any features or functionality of the Application, to any third party for any reason, including by making the Application available on a network where it is capable of being accessed by more than one device at any time;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(f)  remove, disable, circumvent, or otherwise create or implement any workaround to any copy protection, rights management, or security features in or protecting the Application;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(g)  Use the Website in any manner that could disable, overburden, damage, or impair the site or interfere with any other party's use of the Website, including their ability to engage in real time activities through the Website;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(h)  Use any robot, spider or other automatic device, process or means to access the Website or Application for any purpose, including monitoring or copying any of the material on the Website or Application;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(i)  Use any manual process to monitor or copy any of the material on the Website or Application or for any other unauthorized purpose without our prior written consent;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(j)  Use any device, software or routine that interferes with the proper working of the Website or Application;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(k)  Introduce any viruses, trojan horses, worms, logic bombs or other material which is malicious or technologically harmful;</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(l)  Attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Website or Application, the server on which the Website or Application is stored, or any server, computer or database connected to the Website or Application; or </Text>
        <Text style={{...classes.text, ...props.textStyle}}>(m)  Attack the Website or Application via a denial-of-service attack or a distributed denial-of-service attack or otherwise attempt to interfere with the proper working of the Website or Application.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>3.  <Text style={classes.underline}>Reservation of Rights</Text>. You acknowledge and agree that the Website and/or Application is provided under license, and not sold, to you. You do not acquire any ownership interest in the Website and/or Application under this Agreement, or any other rights thereto other than to use the Website and/or Application in accordance with the license granted, and subject to all terms, conditions, and restrictions, under this Agreement. J. J. Keller and its licensors and service providers reserve and shall retain their entire right, title, and interest in and to the Website and Application, including all copyrights, trademarks, and other intellectual property rights therein or relating thereto, except as expressly granted to you in this Agreement.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>4.  <Text style={classes.underline}>Collection and Use of Your Information</Text>.  You acknowledge that when you use the Website or when you download, install, or use the Application, J. J. Keller may use automatic means (including, for example, cookies and web beacons) to collect information about your use of the Website and/or Application and about your Device. You also may be required to provide certain information about yourself in order to download, install, or use the Application or certain of its features or functionality, and the Website and/or Application may provide you with opportunities to share information about yourself with J. J. Keller and others.  All information we collect through or in connection with the Website and Application (including, without limitation, de-identified and aggregated data) is further described in and subject to our <Text style={classes.link} onPress={() => (props.handleNavigation && props.handleNavigation(PrivacyPolicy, 'PrivacyPolicy'))}>Privacy Policy</Text> and applicable law. By using the Website and/or downloading, installing, using, and providing information to or through this Application, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>5.  <Text style={classes.underline}>Updates</Text>. J. J. Keller may from time to time in its sole discretion develop and provide Application updates, which may include upgrades, bug fixes, patches, other error corrections, and/or new features (collectively, including related documentation, "Updates"). Updates may also modify or delete in their entirety certain features and functionality. You agree that J. J. Keller has no obligation to provide any Updates or to continue to provide or enable any particular features or functionality. Based on your Device settings, when your Device is connected to the internet either:</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(a)  the Application will automatically download and install all available Updates; or</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(b)  you may receive notice of or be prompted to download and install available Updates.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>You shall promptly download and install all Updates and acknowledge and agree that the Application or portions thereof may not properly operate should you fail to do so. You further agree that all Updates will be deemed part of the Application and be subject to all terms and conditions of this Agreement.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>6.  <Text style={classes.underline}>Third-Party Materials</Text>. The Website and Application may display, include, or make available third-party content (including data, information, applications, and other products, services, and/or materials) or provide links to third-party websites or services, including through third-party advertising ("Third-Party Materials"). You acknowledge and agree that J. J. Keller is not responsible for Third-Party Materials, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. J. J. Keller does not assume and will not have any liability or responsibility to you or any other person or entity for any Third-Party Materials. Third-Party Materials and links thereto are provided solely as a convenience to you, and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>7.  <Text style={classes.underline}>Term and Termination</Text>.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(a)  The term of Agreement commences when you use the Website or install the Application and will continue in effect until terminated by you or J. J. Keller as set forth in this Section 7; provided, however, any termination of this Agreement shall not terminate this Agreement with respect to your use of the Website.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(b)  You may terminate this Agreement by deleting the Application and all copies thereof from your Device.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(c)  J. J. Keller may terminate this Agreement at any time without notice. In addition, this Agreement will terminate immediately and automatically without any notice if you violate any of the terms and conditions of this Agreement.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(d)  Upon termination:</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(i)  all rights granted to you under this Agreement will also terminate; and</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(ii) you must cease all use of the Application and delete all copies of the Application from your Device and account.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>(e)  Termination will not limit any of J. J. Keller 's rights or remedies at law or in equity.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>8.  <Text style={classes.underline}>Access; Your Account</Text>.  J. J. Keller reserves the right to withdraw or amend the Website or Application, and any service or material we provide on the Website or Application, in J. J. Keller’s sole discretion without notice.  J. J. Keller will not be liable if for any reason all or any part of the Website or Application is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Website or Application, or the entire Website or Application, to users, including registered users.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>You are responsible for making all arrangements necessary for you to have access to the Website or Application.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>To access the Website or some of the resources it offers, you may be asked to provide certain registration details or other information. It is a condition of your use of the Website that all the information you provide on the Website is correct, current and complete. You agree that all information you provide to register with the Website or otherwise, including but not limited to through the use of any interactive features on the Website, is governed by our Privacy Policy, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>You are responsible for any activity that occurs on your Website and/or Application account.  If you choose, or are provided with, a user name, password or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to the Website and/or Application or portions of it using your user name, password or other security information unless otherwise expressly permitted by us. J. J. Keller is not liable for any damage, injury, or harm resulting from your failure to safeguard your password or access information or your device.  You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security.  You also agree to ensure that you exit from your account at the end of each session.  You should use particular caution when accessing your account from a public or shares computer so that others are not able to view or record your password or other personal information.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>By using the Website and/or Application, you agree that, in addition to exercising common sense:</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  You will not create more than one account for yourself.</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  You will not create another account if J. J. Keller has already disabled your account, unless you have J. J. Keller’s written permission to do so.</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  You will not buy, sell, rent, or lease access to your account, username, or a friend link without J. J. Keller’s written permission.</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  You will not share your password.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>·  You will not log in or attempt to access the Application through unauthorized third-party applications or clients.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>If you think that someone has gained access to your account, please immediately reach <Text style={classes.underline}>support@jjkeller.com</Text>.  We have the right to disable any user name, password or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of this Agreement.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>9.  <Text style={classes.underline}>Disclaimer of Warranties</Text>. THE WEBSITE AND APPLICATION ARE PROVIDED TO LICENSEE "AS IS" AND WITH ALL FAULTS AND DEFECTS WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, J. J. KELLER, ON ITS OWN BEHALF AND ON BEHALF OF ITS AFFILIATES AND ITS AND THEIR RESPECTIVE LICENSORS AND SERVICE PROVIDERS, EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO THE WEBSITE AND APPLICATION, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND WARRANTIES THAT MAY ARISE OUT OF COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE, OR TRADE PRACTICE. WITHOUT LIMITATION TO THE FOREGOING, J. J. KELLER PROVIDES NO WARRANTY OR UNDERTAKING, AND MAKES NO REPRESENTATION OF ANY KIND THAT THE APPLICATION WILL MEET YOUR REQUIREMENTS, ACHIEVE ANY INTENDED RESULTS, BE COMPATIBLE, OR WORK WITH ANY OTHER SOFTWARE, APPLICATIONS, SYSTEMS, OR SERVICES, OPERATE WITHOUT INTERRUPTION, MEET ANY PERFORMANCE OR RELIABILITY STANDARDS OR BE ERROR-FREE, OR THAT ANY ERRORS OR DEFECTS CAN OR WILL BE CORRECTED.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR LIMITATIONS ON IMPLIED WARRANTIES OR THE LIMITATIONS ON THE APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO SOME OR ALL OF THE ABOVE EXCLUSIONS AND LIMITATIONS MAY NOT APPLY TO YOU.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>10.  <Text style={classes.underline}>Limitation of Liability</Text>. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL J. J. KELLER OR ITS AFFILIATES, OR ANY OF ITS OR THEIR RESPECTIVE LICENSORS OR SERVICE PROVIDERS, HAVE ANY LIABILITY ARISING FROM OR RELATED TO YOUR USE OF OR INABILITY TO USE THE WEBSITE AND/OR APPLICATION OR FOR: (A) DEATH, PERSONAL INJURY, PROPERTY DAMAGE, LOST PROFITS, COST OF SUBSTITUTE GOODS OR SERVICES, LOSS OF DATA, LOSS OF GOODWILL, BUSINESS INTERRUPTION, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, OR PUNITIVE DAMAGES; AND (B) DIRECT DAMAGES IN AMOUNTS THAT IN THE AGGREGATE EXCEED THE AMOUNT ACTUALLY PAID BY YOU FOR THE SERVICES PROVIDED BY THE WEBSITE AND/OR APPLICATION.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>THE FOREGOING LIMITATIONS WILL APPLY WHETHER SUCH DAMAGES ARISE OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE AND REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE OR EITHER PARTY WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS OF LIABILITY SO SOME OR ALL OF THE ABOVE LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>11.  <Text style={classes.underline}>Indemnification</Text>. You agree to indemnify, defend, and hold harmless J. J. Keller and its officers, directors, managers, members, employees, agents, affiliates, successors, and assigns from and against any and all losses, damages, liabilities, deficiencies, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, or expenses of whatever kind, including attorneys' fees, arising from or relating to your use or misuse of the Website and/or Application or your breach of this Agreement.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>12.  <Text style={[classes.underline, classes.bold]}>Waiver of Class Action Rights and/or Claims</Text>. NEITHER YOU NOR J. J. KELLER SHALL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS, OR ARBITRATE CLAIMS IN A REPRESENTATIVE CAPACITY, INCLUDING WITHOUT LIMITATION AS A REPRESENTATIVE MEMBER OF A CLASS OR IN A PRIVATE ATTORNEY GENERAL CAPACITY, IN CONNECTION WITH ANY DISPUTE. Unless both You and J. J. Keller agree, no arbitrator or judge may consolidate more than one person’s claims or otherwise preside over any form of a representative class proceeding.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>13.  <Text style={classes.underline}>Export Regulation</Text>. The Website and/or Application may be subject to US export control laws, including the US Export Administration Act and its associated regulations. You shall not, directly or indirectly, export, re-export, or release the Website and/or Application to, or make the Website and/or Application accessible from, any jurisdiction or country to which export, re-export, or release is prohibited by law, rule, or regulation. You shall comply with all applicable federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Website and/or Application available outside the US.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>14.  <Text style={classes.underline}>U.S. Government End Users</Text>.  The Application is "Commercial Items," as that term is defined at 48 C.F.R. §2.101, consisting of "Commercial Computer Software" and "Commercial Computer Software Documentation," as such terms are used in 48 C.F.R. §12.212 or 48 C.F.R. §227.7202, as applicable.  Consistent with 48 C.F.R. §12.212 or 48 C.F.R. §§227.7202-1 through 227.7202-4, as applicable, the Application is being licensed to U.S. Government end-users (a) only as "Commercial Items," and (b) with only those rights as are granted to all other end-users pursuant to the terms and conditions herein.  Unpublished-rights are reserved under the copyright laws of the United States.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>15.  <Text style={classes.underline}>Copyright Policy</Text>.  J. J. Keller takes claims of copyright infringement seriously. J. J. Keller will respond to notices of alleged copyright infringement that comply with applicable law. If you believe any materials accessible on or from the Website and/or Application infringe your copyright, you may request removal of those materials (or access to them) from the Website and/or Application by submitting written notification to our Copyright Agent (designated below). In accordance with the Digital Millennium Copyright Act (“DMCA”) the written notice (the “DMCA Notice”) must include substantially the following:</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  Your physical or electronic signature.</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  Identification of the copyrighted work you believe to have been infringed or, if the claim involves multiple works on the Website and/or Application, a representative list of such works.</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  Identification of the material you believe to be infringing in a sufficiently precise manner to allow us to locate that material.</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  Adequate information by which we can contact you (including your name, postal address, telephone number, and, if available, email address).</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  A statement that you have a good faith belief that use of the copyrighted material is not authorized by the copyright owner, its agent, or the law.</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>·  A statement that the information in the written notice is accurate.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>·  A statement, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>Our designated Copyright Agent to receive DMCA Notices is:</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>Jennifer R. Altmann</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>Director of Risk & Compliance</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>3003 Breezewood Lane </Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>P.O. Box 368</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>Neenah, WI 54957-0368</Text>
        <Text style={{...classes.textColor, ...props.textStyle}}>Phone: (920-967-7045)</Text>
        <Text style={{...classes.text, ...props.textStyle}}>Email: jaltmann@jjkeller.com</Text>
        <Text style={{...classes.text, ...props.textStyle}}>If you fail to comply with all of the requirements of the DMCA, your DMCA Notice may not be effective.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>Please be aware that if you knowingly materially misrepresent that material or activity on the Website and/or Application is infringing your copyright, you may be held liable for damages (including costs and attorneys’ fees) under Section 512(f) of the DMCA.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>16.  <Text style={classes.underline}>Data Charges and Mobile Plans</Text>.  You are responsible for any mobile charges that you may incur for using the Application, including text-messaging and data charges. If you are unsure what those charges may be, you should ask your service provider before using the Application.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>17.  <Text style={classes.underline}>Reliance on Information Posted</Text>.  Any information presented on or through the Website and/or Application is made available solely for general information purposes. We do not warrant the accuracy, completeness or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other user of the Website and/or Application, or by anyone who may be informed of any of its contents.  The Website and Application include content provided by third parties, including materials provided by other users, bloggers and third-party licensors and syndicators. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other than the content provided by J. J. Keller, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect the opinion of J. J. Keller. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials provided by any third parties.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>18.  <Text style={classes.underline}>User Contributions</Text>.  The Website and Application may contain message boards, chat rooms, personal pages or profiles, forums, bulletin boards, comment sections and other interactive features (collectively, "Interactive Services") that allow users to post, submit, publish, display, communicate, or transmit to other users, other persons, or J. J. Keller (hereinafter, "post") content or materials (collectively, "User Contributions") on or through the Website and/or Application. Any User Contribution you post will be considered non-confidential and non-proprietary.  By providing any User Contribution, you grant us and our affiliates and service providers, and each of their and our respective licensees, successors and assigns the right to use, reproduce, modify, perform, display, distribute and otherwise disclose to third parties any such material for any purpose.  Because User Contributions are not encrypted or otherwise stored or transmitted as if they contained sensitive information, you understand and acknowledge that you will not include any personal information in your User Contributions.  You further understand and acknowledge that you are responsible for any User Contributions you submit or contribute, and you, not J. J. Keller, have fully responsibility for such content, including its legality, reliability, accuracy and appropriateness.  We are not responsible or liable to you or to any third party for the content or accuracy of any User Contribution.  </Text>
        <Text style={{...classes.text, ...props.textStyle}}>User Contributions must in their entirety comply with all applicable federal, state, location and international laws and regulations, and must not (i) contain any material which is defamatory, obscene, indecent, abusive, offensive, harassing, violent, hateful, inflammatory or otherwise objectionable; (ii) promote sexually explicit or pornographic material, violence, or discrimination based on race, sex, religion, nationality, disability, sexual orientation or age; (iii) infringe any patent, trademark, trade secret, copyright or other intellectual property or other rights of any other person; (iv) violate the legal rights (including the rights of publicity and privacy) of others or contain any material that could give rise to any civil or criminal liability under applicable laws or regulations or that otherwise may be in conflict with this Agreement and our Privacy Policy; (v) be likely to deceive any person; (vi) promote any illegal activity, or advocate, promote or assist any unlawful act; (vii) cause annoyance, inconvenience or needless anxiety or be likely to upset, embarrass, alarm or annoy any other person; (viii) impersonate any person, or misrepresent your identity or affiliation with any person or organization; (ix) involve commercial activities or sales, such as contests, sweepstakes and other sales promotions, barter or advertising; and (x) give the impression that they emanate from or are endorsed by us or any other person or entity, if this is not the case.  We have the right to remove or refuse to post any User Contribution for any or no reason in our sole discretion.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>If You elect to provide or make available to J. J. Keller any suggestions, comments, ideas, improvements or other feedback or materials related to the Website or Application (collectively “Suggestions”), J. J. Keller is free to use, disclose, reproduce, modify, license, transfer and otherwise utilize Your Suggestions in any manner.  You will be entitled to no compensation or credit for, nor gain any right, title or interest in or to any product that J. J. Keller incorporates or otherwise is based upon Your Suggestion, including without limitation any Updates to the Website or Application.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>19.  <Text style={classes.underline}>Online Purchases and Other Terms and Conditions</Text>.  All purchases through the Website or other transactions for the sale of goods or services formed through the Website, as a result of visits made by you are governed by our terms of sale. Additional terms and conditions may also apply to specific portions, services or features of the Website.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>20.  <Text style={classes.underline}>Severability</Text>. If any provision of this Agreement is illegal or unenforceable under applicable law, the remainder of the provision will be amended to achieve as closely as possible the effect of the original term and all other provisions of this Agreement will continue in full force and effect.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>21.  <Text style={classes.underline}>Governing Law</Text>. This Agreement is governed by and construed in accordance with the internal laws of the State of Wisconsin without giving effect to any choice or conflict of law provision or rule. Any legal suit, action, or proceeding arising out of or related to this Agreement or the Application shall be instituted exclusively in the federal courts of the United States or the courts of the State of Wisconsin in each case located in Milwaukee County. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>22.  <Text style={classes.underline}>Limitation of Time to File Claims</Text>. ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE APPLICATION MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES OTHERWISE SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>23.  <Text style={classes.underline}>Entire Agreement</Text>. This Agreement and our Privacy Policy constitute the entire agreement between you and J. J. Keller with respect to the Application and supersede all prior or contemporaneous understandings and agreements, whether written or oral, with respect to the Website and Application.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>24.  <Text style={classes.underline}>Changes to Terms</Text>.  This Agreement may be changed by J. J. Keller from time to time in J. J. Keller’s sole discretion.  We will notify you of any changes by indicating on our home page that this Agreement has changed.  All changes are effective immediately when we post them to the Website and Application and apply to all use of the Website and Application thereafter.  You agree and accept that your continued use of the Website and/or Application following any such amendment will be deemed an acceptance of the amended Agreement.  Please check this Agreement periodically so that you are aware of any changes, as they are binding on you.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>25.  <Text style={classes.underline}>Waiver</Text>. No failure to exercise, and no delay in exercising, on the part of either party, any right or any power hereunder shall operate as a waiver thereof, nor shall any single or partial exercise of any right or power hereunder preclude further exercise of that or any other right hereunder. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>26.  This Application is provided by J. J. Keller & Associates, Inc., 3003 Breezewood Lane, Neenah, WI 54956.  If You have any questions, complaints or claims with respect to the Application or this Agreement, You may contact J. J. Keller at (800) 327-1342 or send an email to <Text style={classes.underline}>support@jjkeller.com</Text>.</Text>
        <Text style={{...classes.text, ...props.textStyle}}>Copyright 2019 J. J. Keller & Associates, Inc.</Text>
    </>
)};

// const EulaText = withTheme(EulaTextComponent);
// export { EulaText };

export { EulaTextComponent };